### ISSUE TITLE
Program closes as soon as it opens

### ISSUE THREAD

**Issue by WetEgg** [LJW-Dev/Modern-Warfare-FastFile-Extractor#3]
Whether I drag and drop the ff onto the exe or even try opening it normally it just closes, no idea if I'm using it wrong or maybe something is broken on my end, are there any required things for me to have to use it? Using the new release version

**Comment by zhm86** [comment]
Line 116 of Program.cs should be modified to the following.
                if (args[1].EndsWith(".ff"))

**Comment by LJW-Dev** [comment]
The program is command line only, the README has all the information on how to run it.
